# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: <span class="text-uppercase font-weight-bold text-default">Xivor</span><span class="white-text text-uppercase font-weight-bold">Hub</span>
# title: <b style='color:#bbb; font-weight:900!important;'>Xivor</b><span>Hub</span>
description: >- # this means to ignore newlines until "baseurl:"
  XivorHub is an information hub for WvW builds and tactics.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xivor.ga" # the base hostname & protocol for your site, e.g. http://example.com
excerpt_separator: "<!--more-->"

# Site settings
logo: /assets/img/logos/logo-512.svg
favicon: /assets/img/logos/favicon.ico
navbar-logo: /assets/img/logos/logo-256.svg
primary-color: 1A503E
bg-image: /assets/img/logos/bg.jpg

# Author settings
author:
  name: Roger Lee Cormier
  alias: Xivor
  email: rogerleecormier@gmail.com
  github: xivor/xivor.github.io
  youtube: UCQm3mI-FElTqMPWkvQOE7_A
  twitter:
  twitch: xivor
  facebook:
  linkedin: rogerleecormier
  instagram:
  pinterest:
  google:
  feedburner:

# Build settings
markdown: kramdown

# Collection settings
collections:
  guides:
    output: true
    sort by: order
  builds:
    output: true
    sort by: order

# Plugins in use

# GW2 info
gwiki:
  url: https://wiki.guildwars2.com/wiki/Main_Page

# Permalinks
#permalink: /:title/
#permalink: /:categories/:title/
#permalink: /:year/:month/:day/:title.html

# Finding solution for pagination, now is disabled
#paginate: 6

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude: ["config.ru", "Gemfile", "Gemfile.lock", "vendor"]
